[colors.primary]
background = "#15141b"
foreground = "#edecee"

[colors.cursor]
text = "#15141b"
cursor = "#a277ff"

[colors.vi_mode_cursor]
text = "#15141b"
cursor = "#a277ff"

[colors.search.matches]
foreground = "#15141b"
background = "#ffca85"

[colors.search.focused_match]
foreground = "#15141b"
background = "#ff6767"

[colors.footer_bar]
foreground = "#15141b"
background = "#edecee"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#110f18"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#8464c6"
cyan = "#61ffca"
white = "#edecee"

[colors.bright]
black = "#4d4d4d"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#c17ac8"
cyan = "#61ffca"
white = "#edecee"
